---
- hosts: localhost
  connection: local

  vars_files:
    - config.yml

  roles:
    - role: setup_homebrew
    - role: setup_dotfiles
      when: configure_dotfiles
    - role: setup_terminal
      when: configure_terminal
    - role: setup_macos
      when: configure_osx
