---
- name: Check if Go is installed
  command: go version
  register: go_installed
  ignore_errors: true

- name: Install Go
  homebrew:
    name: go
    state: latest
  when: go_installed is failed

- name: Get the latest release of gucci
  uri:
    url: https://api.github.com/repos/noqcks/gucci/releases/latest
    return_content: yes
  register: json

- name: Download gucci
  get_url:
    url: "https://github.com/noqcks/gucci/releases/download/{{ json.json.tag_name }}/gucci-{{ json.json.tag_name }}-darwin-amd64"
    dest: "/tmp/gucci"
    mode: '0755'

- name: Check if gucci is installed
  command: gucci --version
  register: gucci_installed
  ignore_errors: true

- name: Confirm gucci replacement with the user
  pause:
    prompt: "Gucci v{{ gucci_installed.stdout.split(' ')[2] }} already exists in /usr/local/bin. Do you want to replace it with {{ json.json.tag_name }}? (yes/no)"
  register: confirm_replace
  when: gucci_installed is not failed

- name: Move gucci to /usr/local/bin
  command: mv /tmp/gucci /usr/local/bin/gucci
  become: true
  when: gucci_installed is failed or (confirm_replace is defined and confirm_replace.user_input | lower == 'yes')